add_newline = true

command_timeout = 1000

format = """
$all\
$fill\
$cmd_duration\
$time\
$docker_context\
$package\
$container\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$lua\
$nodejs\
$python\
$ruby\
$rust\
$terraform\
$line_break\
$jobs\
$status\
$shell\
$character\
"""

[fill]
symbol = " "

[cmd_duration]
min_time = 0
format = '\[[祥$duration]($style)\]'

[directory]
read_only = " "

[docker_context]
format = '\[[$symbol$context]($style)\]'
symbol = " "

[elixir]
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'
symbol = " "

[elm]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[erlang]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[git_branch]
format = '\[[$symbol$branch]($style)\]'
symbol = " "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[helm]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[hg_branch]
format = '\[[$symbol$branch]($style)\]'
symbol = " "

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[lua]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'
symbol = " "

[nodejs]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[package]
format = '\[[$symbol$version]($style)\]'
symbol = " "

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
symbol = " "

[ruby]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[rust]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[shell]
disabled = false
format = "[$indicator]($style)"
unknown_indicator = "?sh"
fish_indicator = ""

[sudo]
format = '\[[$symbol]\]'

[terraform]
format = '\[[$symbol$workspace]($style)\]'

[username]
format = '\[[$user]($style)\]'

[aws]
disabled = true

[battery]
disabled = true

[cmake]
disabled = true

[cobol]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[dotnet]
disabled = true

[gcloud]
disabled = true

[haskell]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[ocaml]
disabled = true

[openstack]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[pulumi]
disabled = true

[purescript]
disabled = true

[red]
disabled = true

[scala]
disabled = true

[swift]
disabled = true

[vagrant]
disabled = true

[vlang]
disabled = true

[zig]
disabled = true
